---
title             : "Indirect effect of sleep on abdominal pain through daytime dysfunction in adults with irritable bowel syndrome"
shorttitle        : "Daytime function, sleep, and pain in IBS"

author: 
  - name          : "Anthony Cifre"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - "Conceptualization"
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"

affiliation:
  - id            : "1"
    institution   : "University of Houston"


authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  **Study Objectives**: Sleep deﬁciency, psychological distress, daytime dysfunction, and abdominal pain are common in adults with irritable bowel syndrome. Prior research on individuals with chronic pain has identiﬁed the indirect effect of sleep on pain through psychological distress or daytime dysfunction; however, this effect is less clear in irritable bowel syndrome. The purpose of this study was to examine potential indirect effects of sleep on abdominal pain symptoms simultaneously through psychological distress and daytime dysfunction in adults with irritable bowel syndrome.
  
  **Methods**: Daily symptoms of nighttime sleep complaints (sleep quality and refreshment), psychological distress, daytime dysfunction (fatigue, sleepiness, and difﬁculty concentrating), and abdominal pain were collected in baseline assessments from 2 randomized controlled trials of 332 adults (mean age 42 years and 85% female) with irritable bowel syndrome. Structural equation modeling was used to examine the global relationships among nighttime sleep complaints, psychological distress, daytime dysfunction, and abdominal pain.
  
  **Results**: The structural equation modeling analyses found a strong indirect effect of poor sleep on abdominal pain via daytime dysfunction but not psychological distress. More than 95% of the total effect of nighttime sleep complaints on abdominal pain was indirect.
  
  **Conclusions**: These ﬁndings suggest that the primary impact of nighttime sleep complaints on abdominal pain is indirect. The indirect effect appears primarily through daytime dysfunction. Such understanding provides a potential avenue to optimize personalized and hybrid behavioral interventions for adults with irritable bowel syndrome through addressing daytime dysfunction and sleep behaviors. Additional study integrating symptoms with biological markers is warranted to explore the underlying mechanisms accounting for these symptoms.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "irritable bowel syndrome, sleep, pain, daytime dysfunction, psychological distress"
wordcount         : "X"

bibliography      : "r-references.bib"

floatsintext      : no
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}

# Load Required Packages
if (!require("pacman")) install.packages("pacman")
pacman::p_load("dplyr", "foreign", "readxl", "tidyr", "rstatix", "tidyverse", 
               "ggpubr", "lme4", "lmerTest", "car", "haven", "lavaan", "papaja")

#options(scipen=0) # yes scientific notation
#options(scipen=999) # no scientific notation
r_refs("r-references.bib")
```

# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

```{r data-preparation, include=FALSE}
# Declare vector with names of variables 
names <- c("Abdominal pain", "Abdominal pain after eating", 
           "Abdominal distention", "Intestinal gas", 
           "Diminished sleep quality", "Unrefreshed sleep", "Fatigue", 
           "Sleepiness during the day", "Hard to concentrate", "Anxiety", 
           "Stress", "Depressive mood")

# Import correlation matrix 
cor_matrix <- as.matrix(read_csv("../../files/data/cor_matrix.csv", col_names = FALSE))
  

# Declare vector with standard deviations for each variable 
sds <- c(26.05, 26.01, 31.82, 
         30.05, 27.18, 27.15, 
         27.25, 25.79, 20.77, 
         22.41, 25.44, 16.51)


# Convert correlation matrix to covariance matrix
cov_matrix <- cor2cov(cor_matrix, sds = sds, names = names)
```

```{r model-specification, include=FALSE}

```



We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
